'use strict';
import {StyleSheet,PixelRatio} from 'react-native';

export default StyleSheet.create({
    container:{
        marginLeft:32/2,
        marginRight:32/2,
        borderBottomWidth:1/PixelRatio.get(),
        borderBottomColor:'#EDEDED'
    },
    titleRow:{
        display:'flex',
        height:32*3/2,
        flexDirection:'row',
        justifyContent:'flex-start',
        alignItems:'center'
    },
    title:{
        fontSize:32/2,
        color:'#333',
        fontWeight:'600'
    },
    cmntContainer:{
        marginTop:20
    },
    cmntUserAndBtn:{
        display:'flex',
        flexDirection:'row',
        justifyContent:'flex-start',
        alignItems:'center',
        height:64/2
    },
    userInfo:{
        flex:3,
        flexDirection:'row',
        justifyContent:'flex-start',
        alignItems:'center'
    },
    userImg:{
        height:64/2,
        width:64/2,
        borderRadius:50,
        marginRight:7
    },
    username:{
        color:'#333',
        fontSize:14
    },
    cmntBtns:{
        flex:1,
        flexDirection:'row',
        justifyContent:'flex-end',
        alignItems:'center'
    },
    good:{
        width:20,
        height:20
    },
    goodnum:{
        fontSize:12,
        color:'#666'
    },
    cmntBodyContainer:{
        marginLeft:110/2 - 32/2,
        marginTop: 4
    },
    cmntBody:{
        color:"#494949",
        lineHeight:24,
        fontSize:16
    },
    cmntBottomBtns:{
        marginTop:4,
        marginLeft:110/2 - 32/2,
        flexDirection:'row',
        justifyContent:'flex-start',
        alignItems:'center'
    },
    cmntTime:{
        fontSize:12,
        color:'#666',
        marginRight:12
    },
    reply:{
        color:'#666',
        fontSize:12,
    },
    cmntUnderLine:{
        height:1/PixelRatio.get(),
        backgroundColor:'#ededed',
        marginLeft:110/2 - 32/2,
        marginRight:32/2,
        marginTop:32/2,
        marginBottom:30/2
    },
    replyListContainer:{
        marginTop:19/2,
        marginLeft:110/2 - 32/2,
        marginRight:32/2,
        backgroundColor:'#f8f8f8',
        borderRadius:4,
        paddingTop:24/2,
        paddingLeft:24/2,
        paddingRight:24/2,
        paddingBottom:24/2
    },
    cmntReplyName:{
        marginBottom:8,
        color:'#937d64',
        fontSize:14
    },
    cmntReplyBody:{
        fontSize:14,
        color:'#666'
    },
    cmntReplyContainerMt:{
        marginTop:32/2
    },
    cmntLookMore:{
        color:'#9e7d64',
        fontSize:14
    }

});
